name: pr

on:
  pull_request:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "Ref: ${{ github.ref }}"
          echo "Base ref: ${{ github.base_ref }}"
          echo "Head ref: ${{ github.head_ref }}"